name: cicd
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true